# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c011c5be6c04524e620b69125c1ebc9abbef427cab18a49adce9ada80e42f5b62cc7825d82a9539ee848f3b532ffeba8b66cf470cab196c7b6d61a86cc9a35e8

test:
  secret_key_base: cd27d46192f36414a947b9092fa809b0fc96d2507d426a0f76d5fc1c5116cd513a0089e6280133ba5bf3a7dff8ef598fc2496c101dde0a13bdb4113db146db84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
